- .gitignore
- README.md
- main.py
Setting up the FastAPI framework, with sample _Hello world_ code.
> #2 Initial FastAPI setup

- .circleci/config.yml
- graph_api/hateoas.py
- graph_api/main.py
- graph_api/manage.py
- graph_api/node/node_model.py
- graph_api/node/node_router.py
- graph_api/node/node_service.py
- graph_api/requirements.txt
- graph_api/tests/test_get.py
- graph_api/tests/test_node_post.py
- graph_api/tests/test_node_service.py
- grisera_api/manage.py
- grisera_api/tests/test_get.py
- tests/graph_api_tests/test_get.py
- tests/graph_api_tests/test_node_post.py
- tests/graph_api_tests/test_node_service.py
My proposition for structure of API and solutions for things like hateoas
> Gris 23.node and label creation

- docker-compose.yml
- graph_api/Dockerfile
- graph_api/database_config.py
- graph_api/main.py
- grisera_api/Dockerfile
- grisera_api/main.py
- grisera_api/tests/test_get.py
Setting deployment environment with _Docker_ and _Docker Compose_
> GRIS-18. Deployment environment

- graph_api/main.py
- graph_api/node/node_service.py
- graph_api/relationship/relationship_model.py
- graph_api/relationship/relationship_router.py
- graph_api/relationship/relationship_service.py
- graph_api/tests/test_relationship_post.py
- graph_api/tests/test_relationship_service.py
Implementation of relationship model, service and router.
> Gris 24.creating relationship between nodes

- graph_api/database_service.py
- graph_api/node/node_service.py
- graph_api/relationship/relationship_model.py
- graph_api/relationship/relationship_service.py
- graph_api/tests/test_property_node_post.py
- graph_api/tests/test_property_node_service.py
- graph_api/tests/test_property_relationship_post.py
- graph_api/tests/test_property_relationship_service.py
Because of solution I've come with I had to do GRIS-33 and GRIS-34 in one branch
> Fix service to return proper information, change tests accordingly

- graph_api/main.py
- grisera_api/main.py
Metadata is visible on documentation pages
> GRIS-41. Add name and description for APIs

- grisera_api/main.py
- grisera_api/observable_information/observable_information_model.py
- grisera_api/observable_information/observable_information_router.py
- grisera_api/observable_information/observable_information_service.py
- grisera_api/tests/test_observable_information_post.py
- grisera_api/tests/test_observable_information_service.py
During our sprint name "Modality" was changed to "Observable information" in Contextual Information. Moreover, I don't think it's very sensible task, because observable information is limited to some set of values.
> Add observable information requests

- grisera_api/graph_api_service.py
- grisera_api/main.py
- grisera_api/participant/participant_model.py
- grisera_api/participant/participant_router.py
- grisera_api/participant/participant_service.py
- grisera_api/participant_state/participant_state_model.py
- grisera_api/participant_state/participant_state_router.py
- grisera_api/participant_state/participant_state_service.py
- grisera_api/tests/test_participant_state_post.py
- grisera_api/tests/test_participant_state_service.py
I've modified the create properties function in graph api service so that we don't have to handle every composite property individually.
> Gris 46.add participant state

- grisera_api/experiment/experiment_model.py
- grisera_api/experiment/experiment_service.py
- grisera_api/graph_api_service.py
- grisera_api/participant_state/participant_state_model.py
- grisera_api/participant_state/participant_state_service.py
- grisera_api/publication/publication_model.py
- grisera_api/publication/publication_service.py
- grisera_api/tests/test_experiment_service.py
With fix of graph api service there was needed some changes in experiment and participant state creation
> Bug fix with nested properties

- graph_api/database_service.py
- graph_api/node/node_model.py
- graph_api/node/node_router.py
- graph_api/node/node_service.py
- graph_api/tests/test_nodes_get.py
- graph_api/tests/test_nodes_get_service.py
- grisera_api/channel/channel_model.py
- grisera_api/channel/channel_service.py
- grisera_api/graph_api_service.py
- grisera_api/main.py
- grisera_api/registered_data/registered_data_model.py
- grisera_api/registered_data/registered_data_router.py
- grisera_api/registered_data/registered_data_service.py
- grisera_api/setup.py
- grisera_api/tests/test_channel_service.py
- grisera_api/tests/test_registered_data_post.py
- grisera_api/tests/test_registered_data_service.py
I used file while initializing channels, because uvicorn starts api with multiple workers. By this it is initialized more than once.
> Initialize channel nodes

- ontology_api/Dockerfile
- ontology_api/hateoas.py
- ontology_api/main.py
- ontology_api/manage.py
- ontology_api/requirements.txt
- ontology_api/tests/test_main.py
Added
- tests
- Dockerfile
- hateoas.py
- manage.py
- requirements.txt
Modified
-main.py
> Added basic files to ontology_api.

- ontology_api/Dockerfile
- ontology_api/hateoas.py
- ontology_api/main.py
- ontology_api/manage.py
- ontology_api/requirements.txt
- ontology_api/tests/test_main.py
Created ontology_api directory
> On 10 dev env

- ontology_api/functions/functions.py
co kolwiek jezezli chcesz komus cos powiedziec, opisac, dlaczego jest to commit,
PS: robię instukcję, jak działa git
> jakaszmian

- ontology_api/functions/functions.py
- ontology_api/tests/test_create_model.py
Added implementation of create_model function in ontology_api/functions/functions.py
Added tests for that functions
> Added implementation

- ontology_api/functions/functions.py
- ontology_api/tests/owlAC_testParticipant.owl
- ontology_api/tests/test_create_model.py
Updated test
Added file for tests
Added generate_id functions
> Updated test

- ontology_api/model/model_router.py
Problem with validating UploadFile class with Pyndatic model. Quick fix based on https://github.com/tiangolo/fastapi/issues/657
> ON-17. Quick fix for problem with processing UploadFile in Pydantic model

- graph_api/database_service.py
- graph_api/node/node_model.py
- graph_api/node/node_router.py
- graph_api/node/node_service.py
- graph_api/tests/test_database_service.py
- graph_api/tests/test_node_service.py
- grisera_api/graph_api_service.py
- grisera_api/services.py
- grisera_api/tests/tests_graphdb_with_signal_values/tests_time_series/test_time_series_with_signal_values_get.py
- grisera_api/tests/tests_graphdb_with_signal_values/tests_time_series/test_time_series_with_signal_values_post.py
- grisera_api/time_series/time_series_model.py
- grisera_api/time_series/time_series_service_graphdb_with_signal_values.py
Example POST requests
```json
{
"observable_information_id": 6,
"measure_id": 0,
"type": "Timestamp",
"signal_values": [
{
"timestamp": 100,
"value": 10
},
{
"timestamp": 200,
"value": 20
}
],
"additional_properties": [
{
"key": "string",
"value": "string"
}
]
}
```
```json
{
"observable_information_id": 6,
"measure_id": 0,
"type": "Epoch",
"signal_values": [
{
"start_timestamp": 10,
"end_timestamp": 15,
"value": 10
},
{
"start_timestamp": 25,
"end_timestamp": 27,
"value": 20
}
],
"additional_properties": [
{
"key": "string",
"value": "string"
}
]
}
````
> Time series - POST and GET

- graph_api/Dockerfile
- grisera_api/Dockerfile
- ontology_api/Dockerfile
After that change `pip install` is not executed every time - only after changing file
> Docker local build cache

- grisera_api/experiment/experiment_service_ontology.py
- grisera_api/ontology_api_service.py
- grisera_api/tests/test_ontology/tests_experiment/test_experiment_service_post.py
In add_instance in OntologyApiService url was corrupt.
> ON-18: Fix add_instance in OntologyApiService

- grisera_api/graph_api_service.py
- grisera_api/tests/test_graph_api_service.py
- grisera_api/tests/tests_graphdb/tests_time_series/test_time_series_router_post_transformation.py
- grisera_api/tests/tests_graphdb_with_signal_values/tests_time_series/test_time_series_with_signal_values_post_transformation.py
- grisera_api/tests/tests_graphdb_with_signal_values/tests_time_series/tests_transformation/test_time_series_transformation_quadrants.py
- grisera_api/tests/tests_graphdb_with_signal_values/tests_time_series/tests_transformation/test_time_series_transformation_resample.py
- grisera_api/time_series/helpers.py
- grisera_api/time_series/time_series_model.py
- grisera_api/time_series/time_series_router.py
- grisera_api/time_series/time_series_service.py
- grisera_api/time_series/time_series_service_graphdb_with_signal_values.py
- grisera_api/time_series/transformation/TimeSeriesTransformation.py
- grisera_api/time_series/transformation/TimeSeriesTransformationFactory.py
- grisera_api/time_series/transformation/TimeSeriesTransformationQuadrants.py
- grisera_api/time_series/transformation/TimeSeriesTransformationResample.py
example requests
```json
{
"name": "quadrants",
"source_time_series_ids": [
0,
7
],
"destination_observable_information_id": 0,
"destination_measure_id": 0,
"additional_properties": [
{
"key": "origin_y",
"value": 3
},
{
"key": "origin_x",
"value": 15
}
]
}
```
```json
{
"name": "resample_nearest",
"source_time_series_ids": [
6
],
"destination_observable_information_id": 0,
"destination_measure_id": 0,
"additional_properties": [
{
"key": "period",
"value": 50
},
{
"key": "some_other_param",
"value": 15
}
]
}
```
> Time series - POST transformation

- ontology_api/role/role_model.py
- ontology_api/role/role_router.py
- ontology_api/role/role_service.py
- ontology_api/tests/test_role_router.py
- ontology_api/tests/test_role_service.py
Delete all relationships of an individual
> ON-35: delete roles

- grisera_api/activity/activity_router.py
- grisera_api/activity/activity_service.py
- grisera_api/activity/activity_service_graphdb.py
Added POST,DELETE and PUT for Activity
> Added POST,DELETE and PUT for Activity

- grisera_api/arrangement/arrangement_router.py
- grisera_api/arrangement/arrangement_service.py
- grisera_api/arrangement/arrangement_service_graphdb.py
- grisera_api/measure_name/measure_name_router.py
- grisera_api/measure_name/measure_name_service.py
- grisera_api/measure_name/measure_name_service_graphdb.py
Created ADD,PUT and DELETE functionalities for arrangements and measure names
> RIRA-25/26

- ontology_api/instance/instance_router.py
- ontology_api/instance/instance_service.py
- ontology_api/tests/test_instance_router.py
- ontology_api/tests/test_instance_service.py
implementation of delete function instance
> ON-33: Delete instance
